# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
---
# Site settings
title: Gravitas Energy
url:  http://www.gravitasenergy.com.au
feed-url: /feed.xml
description: "Gravitas Energy partners with your business to cut energy costs and convert you to sustainable power, all without interrupting the day-to-day running of your business, and saving you money. The Gravitas Energy home office is in Port Melbourne, Victoria, Australia."
keywords: "solar energy, sustainable power, energy supplier, Melbourne Victoria Australia"

# Collections
collections:
	content-home:
		title: content-home
		output: false
	uploads:
		title: Uploads
		output: true

# Build settings
markdown: kramdown

exclude:
- node_modules
- README.markdown
- package.json
- gulp.js
- gulpfile.js
